# Generated by Django 5.0.4 on 2024-04-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_delete_accounts_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='customuser',
            new_name='name',
        ),
    ]
